/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.SwingUtilities;
import pso1.Cola;
import pso1.Nodo;
import pso1.Proceso;

/**
 *
 * @author SebasBD
 */
public class ColaPane extends javax.swing.JPanel {
    
    private Cola<Proceso> colaProcess;

    /**
     * Creates new form ColaPane
     */
    public ColaPane(String titulo, Cola<Proceso> cola) {
        initComponents();
        this.colaProcess = cola;
    }
    
    public void actualizarCola(javax.swing.JPanel container) {
        SwingUtilities.invokeLater(() -> {
            container.removeAll(); // Limpia el contenedor

            Nodo<Proceso> nodoActual = colaProcess.getFront(); // Accede al primer nodo
            while (nodoActual != null) {
                Proceso proceso = nodoActual.getData();
                ProcessPane panelProceso = new ProcessPane(proceso);
                container.add(panelProceso); // Agrega el panel del proceso
                nodoActual = nodoActual.getSiguiente(); // Avanza al siguiente nodo
            }

            container.revalidate(); // Refresca la interfaz
            container.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
