/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import pso1.CPU;

/**
 *
 * @author SebasBD
 */
public class CPUPane extends javax.swing.JPanel {

    /**
     * Creates new form CPUPane
     */
    private CPU cpu;
    public CPUPane(CPU cpu) {
        this.cpu = cpu;
        initComponents();
        actualizarInterfaz();
        this.setMinimumSize(new java.awt.Dimension(300, 200)); // PROBAR LUEGO INTERFAZ Y VER QUE TAMAÑO
        this.setPreferredSize(new java.awt.Dimension(300, 200));
        this.setMaximumSize(new java.awt.Dimension(300, 200));
        
    }
    
    public void actualizarInterfaz() {
        idCPULabel.setText(String.valueOf(cpu.getsId()));
        
 
        // Actualiza los labels con los datos del CPU y su proceso
        nameLabel.setText(cpu.getCurrentProcess() != null ? cpu.getCurrentProcess().getName() : "System");
        idLabel.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getProcess_id()) : "None" );
        pcLabel.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getPc()) : "None");
        marLabel.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getMar()) : "None");
        statusLabel.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getStatus()) : "None");
        typeLabel.setText(cpu.getCurrentProcess() != null ? cpu.getCurrentProcess().getType() : "None");
    }
    
    public void actualizarProceso() {
        
        actualizarInterfaz();
    }
    
    public void freeCPU(){
        nameLabel.setText("Sin proceso");
        idLabel.setText("None");
        pcLabel.setText("None");
        marLabel.setText("None");
        statusLabel.setText("None");
        typeLabel.setText("None");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idCPULabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        pcLabel = new javax.swing.JLabel();
        marLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setText("CPU ");

        idCPULabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        idCPULabel.setText("0");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel11.setText("Proceso en ejecución: ");

        jLabel15.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel15.setText("ID: ");

        jLabel16.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel16.setText("Status:");

        jLabel17.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel17.setText("PC:");

        jLabel18.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel18.setText("MAR:");

        jLabel19.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel19.setText("Tipo:");

        nameLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        nameLabel.setText("nombre");

        idLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        idLabel.setText("id");

        statusLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        statusLabel.setText("estado");

        pcLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        pcLabel.setText("0");

        marLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        marLabel.setText("0");

        typeLabel.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        typeLabel.setText("I/O bound");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(statusLabel)
                    .addComponent(pcLabel)
                    .addComponent(marLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(idCPULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idCPULabel))
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(statusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(pcLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nameLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(marLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(typeLabel))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idCPULabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel marLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
